### ISSUE TITLE
Integrate with Redux DevTools

### ISSUE THREAD

**Issue by robchristian** [rm-rf-etc/simple-shared-state#10]
The features of the redux devtools extension are generally applicable to weir, so we should provide an integration.
https://github.com/zalmoxisus/redux-devtools-extension

![](https://cloud.githubusercontent.com/assets/7957859/18002950/aacb82fc-6b93-11e6-9ae9-609862c18302.png)

**Comment by amark** [comment]
Woah, this looks fancy! :O so cool.

**Comment by Dletta** [comment]
@rm-rf-etc 
What happens if you just integrate with your react via 
https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Integrations.md
.
Will that allow you to inspect gun as well?

I don't use react or redux (don't really know how they work underneath), more of a data structure and gun guy

**Comment by rm-rf-etc** [comment]
@Dletta wow, what an excellent find! Thank you for this, I will need some time to review.

Pretty sure the answer to your question is no. React is very data agnostic, while redux (with redux devtools) is data-zealous. Redux exists purely for the purpose of telling developers how they should manage their data (and this helps a lot because otherwise opinions vary wildly).

So react exposes a method that redux (or anything else) can call to trigger a redraw on a component, and redux takes a component via `connect( ... )`, so it can trigger redraws when it dictates. React just waits for these methods to be called and that drives the virtual DOM.

So redux devtools and react have absolutely no concept of each other as far as I am aware. There is a *react* devtools, but this is specific to react, and has no concept of redux.

[edit]

OH, you were talking about these. https://github.com/zalmoxisus/redux-devtools-extension/blob/master/docs/Integrations.md#inspect-react-props

I will have to see what these can accomplish. Without a connection to a global store, I wonder how devtools can draw the entire state. And in the case of redux and weir, we can have data which components aren't receiving, but we still want to see this in devtools.

**Comment by rm-rf-etc** [comment]
If you need to play around with devtools to see what it provides, install the chrome extension and try these.

https://codesandbox.io/s/5w8pqw6pm4
![Screenshot 2019-09-12 15 37 41](https://user-images.githubusercontent.com/5067463/64825806-6725da00-d573-11e9-8f0c-5052a1509325.png)

https://codesandbox.io/s/2ov1j4zpm0
![Screenshot 2019-09-12 15 40 49](https://user-images.githubusercontent.com/5067463/64825898-c1bf3600-d573-11e9-9745-3687a6544430.png)

**Comment by rm-rf-etc** [comment]
Done
